### ISSUE TITLE
Money from sale of auctions taking hours to deliver not being delivered at all

### ISSUE THREAD

**Issue by Elfsbeth** [Helios-Empire/Helios-Tracker#36] opened 2015-08-17 18:29 UTC
I have an issue with the email delivery of proceeds from the sale of auctions. I receive emails with no money attached which say something like, "Item Sold: Linen Cloth (Buy out), Purchased by: XXXX, Amount pending: 1g 50s, Amount not yet sent, Estimated delivery time 4:56 AM". The delivery time comes and goes and there are no proceeds. I have only eventually received some of the proceeds, others not at all. Some of the email notices telling me I have amounts pending have disappeared from my mailbox with nothing ever sent.

I certainly hope this is not "working as intended" and is, in fact, a hack! If it is the system for delivering auction proceeds, there should not be more than an hour delay in getting the proceeds once the auction is complete or, at the very least, they should be delivered by the time stated in the email.

**Comment by dikkedeur** [comment] 2015-08-18 05:35
i did testing and im not able to reproduce this bug.
i got my item sold got mail that it was pending instant.
after 1 hour i got the money.

**Comment by dikkedeur** [comment] 2015-08-18 10:17
![schermafbeelding 2015-08-18 om 10 39 51](https://cloud.githubusercontent.com/assets/11842306/9327653/ea7b4cec-45a2-11e5-86e7-9fd3acfb327f.png)

you see above is the mail that says that i will get my money around 10:34 AM

and next is around 10:40

![schermafbeelding 2015-08-18 om 10 39 58](https://cloud.githubusercontent.com/assets/11842306/9327665/0a69e4be-45a3-11e5-82ea-85a676d0c959.png)

**Comment by dikkedeur** [comment] 2015-08-26 06:35
not able to reproduce...  closing

**Closed as completed by dikkedeur** 2015-08-26 06:35 UTC
