### ISSUE TITLE
When Rank 2 Faerie Fire (Feral) is bought it no longer shows it having been learned in talent tree

### ISSUE THREAD

**Issue by blabsalot** [Helios-Empire/Helios-Tracker#29] opened 2015-08-16 05:41 UTC

**Comment by dikkedeur** [comment] 2015-08-16 07:36
i'm not able to reproduce this bug as you describe, can you please do a step by step guide on how to reproduce?? after all its a spell learned by the trainer, and i learned it all up to rank5 and i didnt notice anything weird.

**Comment by flinta423** [comment] 2015-08-16 10:39
It's a talent in the feral tree. I experienced it once I learned a higher rank from the trainer and then logging out. resulting in 1 missing talent point.

// Flinta

**Comment by dikkedeur** [comment] 2015-08-16 10:53
okay was now able to reproduce, it gets reset to 0.
you are after that able to buy rank3 and rank 4, but rank2 gets also back in the option to buy..

i have made some extra screens to make it more clear for the devs will handle that out.

**Comment by dikkedeur** [comment] 2015-12-05 12:39
duplicate of https://github.com/Helios-Empire/Helios-Tracker/issues/19

**Closed as completed** 2015-12-05 12:39 UTC
Labels: Class: Druid, Spell, Duplicate
