### ISSUE TITLE
Winder Rider disappearing

### ISSUE THREAD

**Issue by ghost** [Helios-Empire/Helios-Tracker#120] opened 2016-01-02 10:37 UTC
Something interesting that started happening in Outland, hopefully the screenshot shows. But basically when changing zones on the path the wind rider disappears and your character is show swimming in the air, rather funny.

![wowscrnshot_010216_033431](https://cloud.githubusercontent.com/assets/13941340/12074162/2f22cab2-b102-11e5-8f27-9cdb985b4627.jpg)

**Comment by dikkedeur** [comment] 2016-01-02 11:02
totally confirmed

caused by too fast update on the grid VisitNearbyCells, will be fixed in next core update.
Dont worry it doesnt trigger our anticheat system, so its visual and no actions will be taken.
i will close this topic since it will be in next core update be fixed.. if it then still persist feel free to reply to reopen the issue.

**Closed as completed by dikkedeur** 2016-01-02 11:02 UTC
Labels: Misc, MovementGenerators

**Comment by dikkedeur** [comment] 2016-01-03 14:45
another thing..
what client are you using, on my mac i still have the same problem, thats why i need to debug where it comes from.
i thought it would be fixed but it still seems not.
i use a windows client in win config on my mac, so that might be the problem im not sure though.

**Comment by ghost** [comment] 2016-01-04 00:05
I was hoping to respond before you closed, but i'm currently using Windows 7 Pro.

**Comment by dikkedeur** [comment] 2016-01-04 06:39
did some changes and is working correctly now, its not client related thanks for the responce :+1:
