### ISSUE TITLE
The Ogre of Feralas: 

### ISSUE THREAD

**Issue by MkzyKTA** [Helios-Empire/Helios-Tracker#221] opened 2016-03-31 20:41 UTC
Kind of bug: Quest: The Oges of Feralas: http://db.helios-empire.eu/?quest=2975 
                    NPC: Gordunni Ogre Mage: http://db.helios-empire.eu/?npc=5237 
                    Bug: Gordunni Ogre Mage is to highlevel for that area - should be arround lvl 43.

How it should work?: The Ogre Mage should be arround lvl 43 like the quest is, instead of being a boss :)

Operating System: Windows 10

Screenshot: http://www.bilder-upload.eu/show.php?file=7a9a13-1459458141.png

**Comment by dikkedeur** [comment] 2016-03-31 20:52
the problem is that max level is 41-12 and 12 is ehhh not correct.

so i will fix this and also add proper scripting to that npc, so that it works better.
will be fixed on next core update.

thanks for the report.

**Closed as completed** 2016-03-31 20:53 UTC
