### ISSUE TITLE
Bugged quest causes server crash

### ISSUE THREAD

**Issue by Inyu** [Helios-Empire/Helios-Tracker#85] opened 2015-08-20 15:31 UTC
i think the quest "The Seers's Relic" crashes the server no real proof tho.
I tried it three times and the server crashed at the exact same time in the quest.

**Comment by dikkedeur** [comment] 2015-08-20 16:11
yup the crashlogs show that that is indeed the cause. thanks for letting us know,

**Comment by HEGladios** [comment] 2015-08-20 17:06
Crash will be fixed after next core update. Quest may still not function properly, which will need a separate report.

**Closed as completed by HEGladios** 2015-08-20 17:06 UTC
Labels: Quest
