### ISSUE TITLE
Tirisfal Bug Report

### ISSUE THREAD

**Issue by nyrpha** [Helios-Empire/Helios-Tracker#55] opened 2015-08-19 04:56 UTC
I am going to list what bugs i encountered while doing the level 1-10 quests for UD.

Rothide Gnolls apply "Curse of Thule" to themselves rather than to the player. Maggot Eye does the same. However it is correctly working on Rothide Mongrels and Graverobbers.

Scarlet Initiates (The Fireball Casters near Deathknell) do not go back to their original location after de-agroing through player walking away. After this, when they are attacked, they instantly teleport back to the original location. Looks like client / server disagreeing about their location.

Greater Duskbat is sometimes not flying, but halfway inside the ground. (happened once, near the Road where Gordo patrols)

At the Solliden Farmstead, the Mobs are sometimes not reacting to being attacked at all. They will continue to walk around and will not attack the player, until they are dead. Observed on both Tirisfal Farmers and Scarlet Warriors.

Pathing on Solliden Farmstead does not go over the wooden fence. When mobs are attacked from the other side, they will walk all the way around the fence.

The quest "Fields of Grief", the portion where you deliver the poisoned pumpkin to the captive scarlet warrior, is completable but does not result in the warrior being killed. Instead he just keeps standing there.

Seeker Thompson in Undercity is stationary, and does not patrol the city.

That's everything i have so far. I will keep collecting what i come across.
Generally, i had a smooth experience and was able to get to level 10 with no broken quests.

**Comment by dikkedeur** [comment] 2015-08-25 11:44
Pathing on Solliden Farmstead does not go over the wooden fence. When mobs are attacked from the other side, they will walk all the way around the fence.

-- Thats normal and blizzlike, since the object is a fence they will go around it, thats part of mmaps.

Rothide Gnolls apply "Curse of Thule" to themselves rather than to the player. Maggot Eye does the same. However it is correctly working on Rothide Mongrels and Graverobbers.

-- That will be fixed in next core update.

At the Solliden Farmstead, the Mobs are sometimes not reacting to being attacked at all. They will continue to walk around and will not attack the player, until they are dead. Observed on both Tirisfal Farmers and Scarlet Warriors.

-- i was not able to reproduce this right away, but will keep an eye on it.

The quest "Fields of Grief", the portion where you deliver the poisoned pumpkin to the captive scarlet warrior, is completable but does not result in the warrior being killed. Instead he just keeps standing there.

-- was a nice thing for me to do, needed to find out how to do it, but i got it working now, after completing the quest it takes roughly 2 minutes for him to DIE a horrible death.. take notice it will take 5 minutes before he respawns.. if in the future this is too long i can change that to a faster respawn rate.

**Comment by dikkedeur** [comment] 2015-08-25 18:42
Seeker Thompson in Undercity is stationary, and does not patrol the city.
added the waypoints... active on next restart.

**Closed as completed by dikkedeur** 2015-08-25 18:42 UTC
