### ISSUE TITLE
Entangling Roots is broken really bad # Druid Spell

### ISSUE THREAD

**Issue by Zoriamo** [Helios-Empire/Helios-Tracker#48] opened 2015-08-18 16:26 UTC
When you cast roots on your target that is not in combat it will work as intended how ever if the target npc is in combat when you cast roots on that npc it will teleport to the current target of the npc.

**Comment by HEGladios** [comment] 2015-08-18 16:40
Duplicate of https://github.com/Helios-Empire/Helios-Tracker/issues/14

**Closed as completed** 2015-08-18 16:40 UTC
