### ISSUE TITLE
Quest "Deathblow to the Legion" 

### ISSUE THREAD

**Issue by Inyu** [Helios-Empire/Helios-Tracker#190] opened 2016-02-27 16:46 UTC
Kind of bug: npc/quest/spell/instance/ ( include a link to helios database please for link look below )
http://db.helios-empire.eu/?quest=10409
What bug do you encounter?:
Socrethar cant be attacked
How to reproduce your bug?:
try attack him
How it should work?:
Socrethar should be attackable
Operating System:
- Please first search before making a new issue on our tracker.
- Please fill in above template to submit a new issue.
- Use always helios database links > http://db.helios-empire.eu to quests/npcs/spells etc.

**Comment by HEguinness** [comment] 2016-03-03 00:23
Quest turning point (Another version of Deathblow to the Legion) is also not working as intended, leaving this here as a note.

**Comment by HEGladios** [comment] 2016-03-03 09:11
Should be fixed after next core update, thanks @HEguinness!

**Closed as completed by HEGladios** 2016-03-03 09:11 UTC
Labels: Loc: Outland, NPC, Quest
